import os
from google.protobuf import json_format
from server.protos.lists_pb2 import Lists
from server.services.serialization import decode_list_from_base64_string


def test_list_data(list_id):
    """
    Test function to examine public list data generated by data_generator.py
    """
    try:
        # Path to the public list data
        file_path = f'server/EBS/public/lists/{list_id}.bin'
        
        # Check if file exists
        if not os.path.exists(file_path):
            return {"error": f"File not found: {file_path}"}
        
        # Read and parse the Lists proto
        lists_proto = Lists()
        with open(file_path, 'rb') as f:
            lists_proto.ParseFromString(f.read())
        
        # Convert to dict and return
        lists = json_format.MessageToDict(lists_proto)
        l = lists.get('listMap').get(list_id)
        encoded = l.get('encoded')
        decoded = decode_list_from_base64_string(encoded, 'list')
        return decoded
        
    except Exception as e:
        return {"error": f"Error examining list data: {str(e)}"}


