//COLORING FOR BACKGROUND

//* BACKGROUND
export const BACKGROUND_COLOR_LIGHT = 0xffffff
export const BACKGROUND_COLOR_DARK = 0x000000

//* BACKGROUND LINES
export const BACKGROUND_LINE_COLOR_LIGHT = 0x333138
export const BACKGROUND_LINE_COLOR_DARK = 0x333138
