//COLORING FOR EDGES


//* EDGE COLOR
export const EDGE_COLOR_LIGHT = 0x26ee19
export const EDGE_COLOR_DARK = 0x26ee19

//* BACKPROPAGATION EDGE COLOR
export const BACKPROP_EDGE_COLOR_LIGHT = 0x00ffff
export const BACKPROP_EDGE_COLOR_DARK = 0x00ffff

//* SELECTED COLOR
export const SELECTED_COLOR_LIGHT = 0xFF0000
export const SELECTED_COLOR_DARK = 0xFF0000

//* NODULE COLOR
export const NODULE_COLOR_LIGHT = EDGE_COLOR_LIGHT
export const NODULE_COLOR_DARK = EDGE_COLOR_DARK
