//COLORING FOR NODES


//* NODE COLOR
export const NODE_COLOR_LIGHT = 0x3d97FF
export const NODE_COLOR_DARK = 0x3d97FF

//* ABSTRACTION NODE COLOR
export const ABS_COLOR_LIGHT = 0x009AA6
export const ABS_COLOR_DARK = 0x009AA6

//* SELECTED COLOR
export const SELECTED_COLOR_LIGHT = 0xFF0000
export const SELECTED_COLOR_DARK = 0xFF0000

//* HIGHLIGHT COLOR
export const HIGHLIGHT_COLOR_LIGHT = 0x0080FF
export const HIGHLIGHT_COLOR_DARK = 0x0080FF

//* MULTICONNECT COLOR
export const MULTICONNECT_COLOR_LIGHT = 0x00FF00
export const MULTICONNECT_COLOR_DARK = 0x00FF00


//COMMIT TREE

//* SAVE NODES
export const SAVE_NODE_COLOR_LIGHT =0x42bcf5
export const SAVE_NODE_COLOR_DARK =0x42bcf5

//* COMMIT NODES
export const COMMIT_NODE_COLOR_LIGHT = 0x26ee19
export const COMMIT_NODE_COLOR_DARK = 0x26ee19