//COLORING FOR PANELS




//* BACKGROUND COLOR
export const PANEL_BACKGROUND_COLOR_LIGHT = 0XFFFFFF
export const PANEL_BACKGROUND_COLOR_DARK = 0x333333

//* TEXT INPUT BACKGROUND
export const TEXT_INPUT_BACKGROUND_LIGHT = 0xf5f5f5
export const TEXT_INPUT_BACKGROUND_DARK = 0x333333

//* TEXT AREA BACKGROUND 
export const TEXT_AREA_BACKGROUND_LIGHT = 0xf5f5f5
export const TEXT_AREA_BACKGROUND_DARK = 0x333333

//* SUB-HEADER BACKGROUND COLOR
export const SUB_HEADER_BACKGROUND_DARK = 0x545454
export const SUB_HEADER_BACKGROUND_LIGHT =  0xf4f4f4






