//COLORING FOR TEXT



//* WEBSITE HEADER
export const SITE_HEADER_TEXT_LIGHT = 0x000000
export const SITE_HEADER_TEXT_DARK = 0xffffff

//* PANEL MAIN HEADING
export const PANEL_MAIN_HEADING_LIGHT = 0x000000
export const PANEL_MAIN_HEADING_DARK = 0xffffff

//* PANEL SUB-HEADINGS
export const PANEL_SUB_HEADING_LIGHT = 0x000000
export const PANEL_SUB_HEADING_DARK = 0x000000

//* TEXT INPUT COLOR
export const TEXT_INPUT_LIGHT = 0X000000
export const TEXT_INPUT_DARK = 0XFFFFFF

//* TEXT AREA COLOR
export const TEXT_AREA_LIGHT = 0X000000
export const TEXT_AREA_DARK = 0XFFFFFF
