//COLORING FOR THUMBNAILS


//GRAPH THUMBNAILS

//* MAIN COLOR
export const GRAPH_THUMBNAIL_MAIN_COLOR_LIGHT = 0xb6bbbf;
export const GRAPH_THUMBNAIL_MAIN_COLOR_DARK = 0xb6bbbf;

//* SELECTED COLOR
export const GRAPH_THUMBNAIL_SELECTED_COLOR_LIGHT = 0x90ef8f;
export const GRAPH_THUMBNAIL_SELECTED_COLOR_DARK = 0x90ef8f;

//* TEXT COLOR
export const GRAPH_THUMBNAIL_TEXT_COLOR_LIGHT = 0x000000;
export const GRAPH_THUMBNAIL_TEXT_COLOR_DARK = 0xffffff;


//ABSTRACTION NODE THUMBNAILS

//* MAIN COLOR
export const ABS_THUMBNAIL_MAIN_COLOR_LIGHT = 0xf56305;
export const ABS_THUMBNAIL_MAIN_COLOR_DARK = 0xf56305;

//* SELECTED COLOR
export const ABS_THUMBNAIL_SELECTED_COLOR_LIGHT = 0x90ef8f;
export const ABS_THUMBNAIL_SELECTED_COLOR_DARK = 0x90ef8f;

//* TEXT COLOR
export const ABS_THUMBNAIL_TEXT_COLOR_LIGHT = 0x000000;
export const ABS_THUMBNAIL_TEXT_COLOR_DARK = 0xffffff;

//* BACKGROUND COLOR
export const ABS_THUMBNAIL_BACKGROUND_COLOR_LIGHT = 0xe5e5e5;
export const ABS_THUMBNAIL_BACKGROUND_COLOR_DARK = 0xe5e5e5;

//OTHER

//* DOTS COLOR
export const DOTS_COLOR_LIGHT = 0xb6bbbf;
export const DOTS_COLOR_DARK = 0xb6bbbf;